import { FormEvent, useEffect, useState } from "react";
import { BarChart3, Bell, Check, Flame, Home, LoaderCircle, Search, Shield, Sparkles, Star, Trophy, Users, X } from "lucide-react";
import type { TeamHubData, TeamSummary } from "./types";
import LeaderboardPage from "./LeaderboardPage";
import PredictionsPage from "./PredictionsPage";
import ModelOutlook from "./ModelOutlook";

type SavedTeam = TeamSummary & { provider_id: string };
type Progress = { level:number; total_xp:number; xp_into_level:number; xp_for_next_level:number; progress_percent:number; current_streak:number; longest_streak:number; last_active_date:string|null };
type Profile = { id:number; display_name:string; primary_team:SavedTeam|null; favorites:SavedTeam[]; progress:Progress; mode:string };
type QuizQuestion = { id:string; question:string; options:string[] };
type DailyQuiz = { quiz_id:string; title:string; questions:QuizQuestion[]; completed:boolean; xp_available:number };
type MatchTeam = { id:string; name:string; short_name?:string|null; tla?:string|null; crest_url?:string|null };
type FanMatch = { id:string; utc_date?:string|null; status?:string|null; competition?:string|null; home_team:MatchTeam; away_team:MatchTeam; source_team_id:string; user_prediction?:"HOME"|"DRAW"|"AWAY"|null };

const navItems=[{label:"Home",icon:Home},{label:"My Team",icon:Shield},{label:"Favorites",icon:Star},{label:"Matches",icon:Trophy},{label:"Predictions",icon:BarChart3},{label:"Daily Quiz",icon:Sparkles},{label:"Leaderboard",icon:Users}];

function App(){
 const [apiStatus,setApiStatus]=useState<"checking"|"online"|"offline">("checking"); const [query,setQuery]=useState(""); const [searching,setSearching]=useState(false); const [searchResults,setSearchResults]=useState<TeamSummary[]>([]); const [searchMessage,setSearchMessage]=useState(""); const [selectedTeam,setSelectedTeam]=useState<TeamHubData|null>(null); const [loadingTeam,setLoadingTeam]=useState(false); const [profile,setProfile]=useState<Profile|null>(null); const [savingPreference,setSavingPreference]=useState(false); const [activePage,setActivePage]=useState("Home");
 async function loadProfile(){const r=await fetch("/api/v1/profile");if(r.ok)setProfile(await r.json())}
 useEffect(()=>{fetch("/api/v1/health").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(()=>setApiStatus("online")).catch(()=>setApiStatus("offline"));loadProfile().catch(()=>undefined)},[]);
 async function searchTeams(e:FormEvent){e.preventDefault();const t=query.trim();if(t.length<2)return;setSearching(true);setSearchMessage("");setSearchResults([]);try{const r=await fetch(`/api/v1/teams/search?q=${encodeURIComponent(t)}`);const p=await r.json();if(!r.ok)throw new Error(p.detail||"Team search failed.");setSearchResults(p.results||[]);if(!p.results?.length)setSearchMessage("No matching teams found.")}catch(e){setSearchMessage(e instanceof Error?e.message:"Team search failed.")}finally{setSearching(false)}}
 async function openTeam(team:TeamSummary|SavedTeam){const id="provider_id" in team?team.provider_id:team.id;setLoadingTeam(true);setSearchMessage("");try{const r=await fetch(`/api/v1/teams/${id}`);const p=await r.json();if(!r.ok)throw new Error(p.detail||"Could not load the team hub.");setSelectedTeam(p);setSearchResults([]);setQuery("")}catch(e){setSearchMessage(e instanceof Error?e.message:"Could not load the team hub.")}finally{setLoadingTeam(false)}}
 async function savePreference(kind:"primary"|"favorite",id:string){setSavingPreference(true);try{const r=await fetch(kind==="primary"?"/api/v1/profile/primary-team":"/api/v1/profile/favorites",{method:kind==="primary"?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider_team_id:id})});if(!r.ok)throw new Error();await loadProfile()}finally{setSavingPreference(false)}}
 async function removeFavorite(id:string){setSavingPreference(true);try{await fetch(`/api/v1/profile/favorites/${id}`,{method:"DELETE"});await loadProfile()}finally{setSavingPreference(false)}}
 const primaryId=profile?.primary_team?.provider_id;const favoriteIds=new Set(profile?.favorites.map(t=>t.provider_id)||[]);
 let page:any=<HomeDashboard profile={profile} onOpen={openTeam} onQuiz={()=>setActivePage("Daily Quiz")} onMatches={()=>setActivePage("Matches")}/>;
 if(activePage==="Daily Quiz")page=<QuizPage onProgress={loadProfile}/>;else if(activePage==="Favorites")page=<FavoritesPage profile={profile} onOpen={openTeam}/>;else if(activePage==="My Team")page=<MyTeamPage profile={profile} onOpen={openTeam}/>;else if(activePage==="Matches")page=<MatchesPage onProgress={loadProfile} profile={profile}/>;else if(activePage==="Predictions")page=<PredictionsPage/>;else if(activePage==="Leaderboard")page=<LeaderboardPage/>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><div><strong>FanSphere</strong><span>V2 Preview</span></div></div><nav>{navItems.map(({label,icon:Icon})=><button className={activePage===label?"nav-item active":"nav-item"} key={label} onClick={()=>{setActivePage(label);setSelectedTeam(null)}}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar-card"><Flame size={21}/><div><span>Daily streak</span><strong>{profile?.progress.current_streak||0} day{profile?.progress.current_streak===1?"":"s"}</strong></div></div></aside><main><header className="topbar"><form className="search search-form" onSubmit={searchTeams}>{searching?<LoaderCircle className="spin" size={18}/>:<Search size={18}/>}<input aria-label="Search teams" placeholder="Search any football team..." value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" className="search-submit" disabled={searching||query.trim().length<2}>Search</button>{(searchResults.length>0||searchMessage)&&<div className="search-popover">{searchMessage&&<p className="search-message">{searchMessage}</p>}{searchResults.map(team=><button type="button" className="search-result" key={team.id} onClick={()=>openTeam(team)}><span className="search-crest">{team.crest_url?<img src={team.crest_url} alt=""/>:(team.tla||team.name.slice(0,2))}</span><span><strong>{team.name}</strong><small>{[team.league_name,team.country].filter(Boolean).join(" · ")||"Football team"}</small></span><span className="result-arrow">→</span></button>)}</div>}</form><div className={`api-status ${apiStatus}`}><span/>{apiStatus==="checking"?"Connecting":apiStatus==="online"?"API online":"API offline"}</div><button className="icon-button" aria-label="Notifications"><Bell size={19}/></button><div className="avatar">PR</div></header><section className="content">{selectedTeam?<TeamHub data={selectedTeam} onClose={()=>setSelectedTeam(null)} primaryId={primaryId} favoriteIds={favoriteIds} saving={savingPreference} onPrimary={id=>savePreference("primary",id)} onFavorite={id=>savePreference("favorite",id)} onUnfavorite={removeFavorite}/>:page}{loadingTeam&&<div className="loading-overlay"><LoaderCircle className="spin" size={28}/><span>Loading team...</span></div>}</section></main></div>}

function MatchesPage({onProgress,profile}:{onProgress:()=>Promise<void>;profile:Profile|null}){
 const [matches,setMatches]=useState<FanMatch[]>([]);const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState<string|null>(null);const [reward,setReward]=useState("");const [expanded,setExpanded]=useState<Set<string>>(new Set());
 async function load(){setLoading(true);try{const r=await fetch("/api/v1/matches");const p=await r.json();if(!r.ok)throw new Error(p.detail||"Could not load matches.");setMatches(p.matches||[]);setNotice(p.notice||"")}catch(e){setNotice(e instanceof Error?e.message:"Could not load matches.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function predict(match:FanMatch,outcome:"HOME"|"DRAW"|"AWAY"){setSaving(match.id);setReward("");try{const r=await fetch(`/api/v1/matches/${match.id}/prediction`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({outcome})});const p=await r.json();if(!r.ok)throw new Error(p.detail||"Prediction failed.");setMatches(ms=>ms.map(m=>m.id===match.id?{...m,user_prediction:outcome}:m));setReward(p.xp_awarded?`Prediction saved · +${p.xp_awarded} XP`:"Prediction updated");await onProgress()}catch(e){setReward(e instanceof Error?e.message:"Prediction failed.")}finally{setSaving(null)}}
 function toggle(teamId:string){setExpanded(current=>{const next=new Set(current);next.has(teamId)?next.delete(teamId):next.add(teamId);return next})}
 const savedTeams=[...(profile?.primary_team?[profile.primary_team]:[]),...(profile?.favorites||[]).filter(t=>t.provider_id!==profile?.primary_team?.provider_id)];
 const groups=savedTeams.map(team=>({team,matches:matches.filter(m=>String(m.home_team.id)===team.provider_id||String(m.away_team.id)===team.provider_id)})).filter(group=>group.matches.length);
 if(loading)return <div className="matches-loading"><LoaderCircle className="spin"/> Loading your matches...</div>;
 return <div className="matches-page">
  <style>{`.team-match-groups{display:grid;gap:28px;margin-top:28px}.team-match-section{padding:0}.team-match-header{display:flex;align-items:center;gap:13px;margin-bottom:13px}.team-match-header img,.team-match-fallback{width:42px;height:42px;object-fit:contain;border-radius:10px;background:#f3f6fa;padding:4px}.team-match-fallback{display:grid;place-items:center;color:#12233a;font-weight:900}.team-match-header>div{flex:1}.team-match-header h2{margin:0;font-size:21px}.team-match-header p{margin:3px 0 0;font-size:12px}.team-match-header .count-chip{white-space:nowrap}.team-match-section .match-list{margin-top:0}.show-more-matches{display:flex;justify-content:center;margin-top:12px}.show-more-matches button{border:1px solid #29445f;border-radius:10px;background:#0b1d30;color:#9cb0c7;padding:9px 14px;font-weight:750}.show-more-matches button:hover{border-color:#7cf3c7;color:#dffbf1}@media(max-width:760px){.team-match-header{align-items:flex-start}.team-match-header .count-chip{margin-left:auto}}`}</style>
  <span className="eyebrow">MATCH CENTER</span><h1>Upcoming matches</h1><p>Fixtures are grouped by the teams you follow so the match center stays easier to scan.</p>
  {reward&&<div className="prediction-toast">{reward}</div>}{notice&&<div className="quiz-complete-note">{notice}</div>}
  {!matches.length?<section className="empty-state"><Trophy size={34}/><h2>No upcoming matches found</h2><p>Follow a club with available fixture data to build this feed.</p></section>:
   groups.length?<div className="team-match-groups">{groups.map(({team,matches:teamMatches})=>{const isOpen=expanded.has(team.provider_id);const shown=isOpen?teamMatches:teamMatches.slice(0,3);return <section className="team-match-section" key={team.provider_id}><div className="team-match-header">{team.crest_url?<img src={team.crest_url} alt=""/>:<span className="team-match-fallback">{team.tla||team.name.slice(0,2)}</span>}<div><span className="eyebrow">{team.provider_id===profile?.primary_team?.provider_id?"PRIMARY TEAM":"FOLLOWING"}</span><h2>{team.name}</h2><p>{teamMatches.length} upcoming match{teamMatches.length===1?"":"es"}</p></div><span className="count-chip">{teamMatches.length}</span></div><div className="match-list">{shown.map(match=><article className="match-card" key={match.id}><div className="match-top"><span>{match.competition||"Football"}</span><time>{match.utc_date?new Date(match.utc_date).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"Date TBA"}</time></div><div className="match-teams"><TeamSide team={match.home_team}/><div className="versus">VS</div><TeamSide team={match.away_team}/></div><div className="prediction-area"><span>YOUR PREDICTION <small>+10 XP first pick</small></span><div className="prediction-buttons"><button disabled={saving===match.id} className={match.user_prediction==="HOME"?"picked":""} onClick={()=>predict(match,"HOME")}>{match.home_team.short_name||match.home_team.name}</button><button disabled={saving===match.id} className={match.user_prediction==="DRAW"?"picked":""} onClick={()=>predict(match,"DRAW")}>Draw</button><button disabled={saving===match.id} className={match.user_prediction==="AWAY"?"picked":""} onClick={()=>predict(match,"AWAY")}>{match.away_team.short_name||match.away_team.name}</button></div></div><ModelOutlook matchId={match.id} homeTeam={match.home_team} awayTeam={match.away_team}/></article>)}</div>{teamMatches.length>3&&<div className="show-more-matches"><button onClick={()=>toggle(team.provider_id)}>{isOpen?`Show fewer ${team.name} matches`:`Show all ${teamMatches.length} ${team.name} matches`}</button></div>}</section>})}</div>:
   <section className="empty-state"><Trophy size={34}/><h2>No grouped fixtures found</h2><p>Refresh your profile or follow a team to organize this match feed.</p></section>}
 </div>
}
function TeamSide({team}:{team:MatchTeam}){return <div className="match-team">{team.crest_url?<img src={team.crest_url} alt=""/>:<div className="mini-crest">{team.tla||team.name.slice(0,2)}</div>}<strong>{team.name}</strong></div>}
function HomeDashboard({profile,onOpen,onQuiz,onMatches}:{profile:Profile|null;onOpen:(team:SavedTeam)=>void;onQuiz:()=>void;onMatches:()=>void}){const team=profile?.primary_team,p=profile?.progress;return <><div className="welcome-row"><div><span className="eyebrow">YOUR FOOTBALL WORLD</span><h1>Good afternoon, {profile?.display_name||"fan"}.</h1><p>{team?`Your home feed starts with ${team.name}.`:"Search for your team and make it your primary team."}</p></div><div className="xp-pill"><span>LEVEL {p?.level||1}</span><strong>{p?.total_xp||0} XP</strong></div></div><div className="progress-card"><div><strong>Level {p?.level||1}</strong><span>{p?.xp_into_level||0} / {p?.xp_for_next_level||500} XP to next level</span></div><div className="progress-track"><span style={{width:`${p?.progress_percent||0}%`}}/></div></div>{team?<section className="hero-card"><div className="team-identity"><div className="crest-placeholder">{team.crest_url?<img className="saved-crest" src={team.crest_url} alt=""/>:team.name.slice(0,2)}</div><div><span className="eyebrow">PRIMARY TEAM</span><h2>{team.name}</h2><p>{[team.league_name,team.country].filter(Boolean).join(" · ")}</p></div></div><div className="hero-actions"><button className="secondary-button" onClick={onMatches}>View Matches</button><button className="primary-button" onClick={()=>onOpen(team)}>Open Team Hub</button></div></section>:<section className="empty-state"><Shield size={34}/><h2>Choose your team</h2><p>Search above, open a team, then select “Make My Team.”</p></section>}<div className="dashboard-grid"><section className="panel"><span className="eyebrow">STREAK</span><h3>{p?.current_streak||0} day streak 🔥</h3><p>Longest streak: {p?.longest_streak||0} days. Complete today's quiz to keep it moving.</p></section><section className="panel quiz-panel"><span className="eyebrow">DAILY QUIZ</span><h3>Earn up to 100 XP</h3><p>Five questions, once-a-day XP, and a streak bonus.</p><button className="primary-button" onClick={onQuiz}>Play Today's Quiz</button></section></div></>}
function QuizPage({onProgress}:{onProgress:()=>Promise<void>}){const [quiz,setQuiz]=useState<DailyQuiz|null>(null);const [answers,setAnswers]=useState<Record<string,number>>({});const [result,setResult]=useState<any>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/v1/quiz/daily").then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.detail||"Quiz unavailable.");return p}).then(setQuiz).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);async function submit(){if(!quiz)return;const r=await fetch("/api/v1/quiz/daily/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quiz_id:quiz.quiz_id,answers})});const p=await r.json();if(!r.ok){setError(p.detail||"Could not submit quiz.");return}setResult(p);await onProgress()}if(loading)return <div className="matches-loading"><LoaderCircle className="spin"/> Loading today's quiz...</div>;if(error)return <section className="empty-state"><Sparkles size={34}/><h2>Quiz unavailable</h2><p>{error}</p></section>;if(!quiz)return null;return <div className="quiz-page"><span className="eyebrow">DAILY CHALLENGE</span><h1>{quiz.title}</h1><p>Five questions · 50 XP completion + 10 XP per correct answer · first completion counts toward your streak.</p>{quiz.completed&&!result&&<div className="quiz-complete-note">You already earned today's XP. You can replay for practice, but XP is awarded only once per day.</div>}{result&&<div className="quiz-result"><strong>{result.correct_count}/{result.total_questions} correct</strong><span>+{result.xp_awarded} XP earned · {result.progress.current_streak} day streak</span></div>}<div className="question-list">{quiz.questions.map((q,i)=><article className="question-card" key={q.id}><span>QUESTION {i+1}</span><h3>{q.question}</h3><div className="answer-grid">{q.options.map((option,index)=><button key={option} className={answers[q.id]===index?"answer selected":"answer"} onClick={()=>setAnswers(a=>({...a,[q.id]:index}))} disabled={!!result}>{answers[q.id]===index?<Check size={16}/>:<span>{String.fromCharCode(65+index)}</span>}{option}</button>)}</div></article>)}</div>{!result&&<button className="primary-button quiz-submit" disabled={Object.keys(answers).length!==quiz.questions.length} onClick={submit}>Submit Quiz</button>}</div>}
function MyTeamPage({profile,onOpen}:{profile:Profile|null;onOpen:(team:SavedTeam)=>void}){const t=profile?.primary_team;if(!t)return <section className="empty-state"><Shield size={34}/><h2>No primary team yet</h2><p>Search for a team and choose “Make My Team.”</p></section>;return <div><span className="eyebrow">MY TEAM</span><h1>Your primary club</h1><div className="saved-team-card"><div className="saved-team-crest">{t.crest_url?<img src={t.crest_url} alt=""/>:t.name.slice(0,2)}</div><div><h2>{t.name}</h2><p>{[t.league_name,t.country].filter(Boolean).join(" · ")}</p></div><button className="primary-button" onClick={()=>onOpen(t)}>Open Team Hub</button></div></div>}
function FavoritesPage({profile,onOpen}:{profile:Profile|null;onOpen:(team:SavedTeam)=>void}){const teams=profile?.favorites||[];return <div><span className="eyebrow">FAVORITES</span><h1>Teams you follow</h1><p>Your personalized football world can include more than one team.</p><div className="favorites-grid">{teams.length?teams.map(t=><button className="favorite-card" key={t.provider_id} onClick={()=>onOpen(t)}><span className="saved-team-crest">{t.crest_url?<img src={t.crest_url} alt=""/>:t.name.slice(0,2)}</span><strong>{t.name}</strong><small>{[t.league_name,t.country].filter(Boolean).join(" · ")}</small></button>):<section className="empty-state"><Star size={34}/><h2>No favorites yet</h2><p>Search for clubs and follow them to see them here.</p></section>}</div></div>}
function TeamHub({data,onClose,primaryId,favoriteIds,saving,onPrimary,onFavorite,onUnfavorite}:{data:TeamHubData;onClose:()=>void;primaryId?:string;favoriteIds:Set<string>;saving:boolean;onPrimary:(id:string)=>void;onFavorite:(id:string)=>void;onUnfavorite:(id:string)=>void}){const t=data.team,isPrimary=primaryId===t.id,isFavorite=favoriteIds.has(t.id);return <div className="team-hub"><button className="close-hub" onClick={onClose}><X size={16}/> Close team hub</button><section className="team-hero"><div className="team-hero-crest">{t.crest_url?<img src={t.crest_url} alt=""/>:t.name.slice(0,2)}</div><div><span className="eyebrow">TEAM HUB</span><h1>{t.name}</h1><p>{[t.league_name,t.country].filter(Boolean).join(" · ")}</p><div className="team-meta">{t.founded&&<span>Founded {t.founded}</span>}{t.venue&&<span>{t.venue}</span>}{t.club_colors&&<span>{t.club_colors}</span>}</div><div className="team-actions"><button className="primary-button" disabled={saving||isPrimary} onClick={()=>onPrimary(t.id)}>{isPrimary?"Your Primary Team":"Make My Team"}</button>{isFavorite?<button className="secondary-button" disabled={saving} onClick={()=>onUnfavorite(t.id)}>Following ✓</button>:<button className="secondary-button" disabled={saving} onClick={()=>onFavorite(t.id)}>+ Follow Team</button>}</div></div></section>{data.notices?.length>0&&<div className="provider-notice"><strong>Data coverage notice</strong>{data.notices.map((n,i)=><p key={i}>{n}</p>)}</div>}<div className="hub-grid"><section className="hub-panel"><div className="section-heading"><div><span className="eyebrow">SQUAD</span><h2>Current players</h2></div><span className="count-chip">{data.squad.length}</span></div>{data.squad.length?<div className="squad-list">{data.squad.slice(0,12).map(p=><div className="player-row" key={p.id}><div className="player-avatar">{p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><strong>{p.name}</strong><span>{p.position||"Player"} · {p.nationality||"—"}</span></div></div>)}</div>:<div className="empty-panel"><Users size={24}/><strong>Squad unavailable</strong><span>This provider does not expose this team's squad on the current plan.</span></div>}</section><section className="hub-panel"><div className="section-heading"><div><span className="eyebrow">UPCOMING</span><h2>Fixtures</h2></div><span className="count-chip">{data.fixtures.length}</span></div>{data.fixtures.length?<div className="fixture-list">{data.fixtures.slice(0,8).map(m=><div className="fixture-row" key={m.id}><span>{m.utc_date?new Date(m.utc_date).toLocaleDateString():"TBA"}</span><strong>{m.home_team.name} <em>vs</em> {m.away_team.name}</strong><small>{m.competition||"Match"}</small></div>)}</div>:<div className="empty-panel"><Trophy size={24}/><strong>Fixtures unavailable</strong><span>Fixture coverage is not available for this team on the current provider plan.</span></div>}</section></div></div>}
export default App;
