import { useState } from "react";

type MatchTeam={name:string;short_name?:string|null};
type Props={matchId:string;homeTeam:MatchTeam;awayTeam:MatchTeam};
type ModelPrediction={available?:boolean;reason?:string;pick:"HOME"|"DRAW"|"AWAY";probabilities:{HOME:number;DRAW:number;AWAY:number};model_version:string;model_type?:string;training_status?:string;disclaimer?:string};

export default function ModelOutlook({matchId,homeTeam,awayTeam}:Props){
 const [model,setModel]=useState<ModelPrediction|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function analyze(){setLoading(true);setError("");try{const qs=new URLSearchParams({home_name:homeTeam.name,away_name:awayTeam.name});const r=await fetch(`/api/v1/ml/predict/${matchId}?${qs}`);const p=await r.json();if(!r.ok)throw new Error(p.detail||"Model prediction unavailable.");if(p.available===false)throw new Error(p.reason||"Model prediction unavailable.");setModel(p)}catch(e){setError(e instanceof Error?e.message:"Model prediction unavailable.")}finally{setLoading(false)}}
 const label=(side:"HOME"|"DRAW"|"AWAY")=>side==="HOME"?(homeTeam.short_name||homeTeam.name):side==="AWAY"?(awayTeam.short_name||awayTeam.name):"Draw";
 const trained=model?.training_status==="trained";
 return <div className="model-outlook"><style>{`.model-outlook{margin-top:12px;padding-top:12px;border-top:1px solid #18314b}.model-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.model-head span{font-size:10px;font-weight:900;letter-spacing:.1em;color:#7cf3c7}.model-head small{display:block;color:#607a95;margin-top:3px}.model-button{border:1px solid #29445f;border-radius:9px;background:#0b1d30;color:#9cb0c7;padding:7px 11px;font-size:11px;font-weight:800}.model-button:hover{border-color:#7cf3c7;color:#e0fff4}.model-button:disabled{opacity:.55}.model-probs{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.model-prob{padding:8px;border-radius:9px;background:#071421;border:1px solid #18314b}.model-prob.best{border-color:#56cfa7;background:rgba(86,207,167,.08)}.model-prob span{display:block;color:#738ca6;font-size:9px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.model-prob strong{display:block;margin-top:3px;font-size:15px}.model-caption,.model-error{margin:8px 0 0!important;font-size:9px!important;line-height:1.4}.model-caption{color:#607a95!important}.model-error{color:#ef9ba1!important}`}</style><div className="model-head"><div><span>MODEL OUTLOOK</span><small>{model?(trained?"FanSphere ML v1":"Recent-form baseline"):"Analyze with FanSphere"}</small></div>{!model&&<button className="model-button" onClick={analyze} disabled={loading}>{loading?"Analyzing...":"Analyze match"}</button>}</div>{model&&<><div className="model-probs">{(["HOME","DRAW","AWAY"] as const).map(side=><div key={side} className={`model-prob ${model.pick===side?"best":""}`}><span>{label(side)}</span><strong>{Math.round(model.probabilities[side]*100)}%</strong></div>)}</div><p className="model-caption">{trained?"EPL logistic-regression model · historical Elo + recent form features.":"Baseline v1 · recent team form only · not a trained ML model yet."}</p></>}{error&&<p className="model-error">{error}</p>}</div>
}
