import { BarChart3, CheckCircle2, Clock3, LoaderCircle, RefreshCw, Target, XCircle } from "lucide-react";
import { useEffect, useState } from "react";

type Prediction = { id:number; match_id:string; home_team_name:string; away_team_name:string; predicted_outcome:"HOME"|"DRAW"|"AWAY"; kickoff_utc?:string|null; created_at?:string|null; actual_outcome?:"HOME"|"DRAW"|"AWAY"|null; result_status:"PENDING"|"CORRECT"|"INCORRECT"; score?:{home:number|null;away:number|null}|null };
type PredictionResponse = { predictions:Prediction[]; total:number; scored:number; correct:number; accuracy_percent:number|null; notice?:string|null };

function outcomeLabel(item:Prediction,outcome:Prediction["predicted_outcome"]|null|undefined){if(outcome==="HOME")return item.home_team_name;if(outcome==="AWAY")return item.away_team_name;if(outcome==="DRAW")return "Draw";return "—"}

export default function PredictionsPage(){
 const [data,setData]=useState<PredictionResponse|null>(null);const [error,setError]=useState("");const [refreshing,setRefreshing]=useState(false);const [filter,setFilter]=useState<"ALL"|"PENDING"|"CORRECT"|"INCORRECT">("ALL");
 async function load(refresh=false){if(refresh)setRefreshing(true);setError("");try{const r=await fetch("/api/v1/matches/predictions");const p=await r.json();if(!r.ok)throw new Error(p.detail||"Could not load predictions.");setData(p)}catch(e){setError(e instanceof Error?e.message:"Could not load predictions.")}finally{if(refresh)setRefreshing(false)}}
 useEffect(()=>{load()},[]);
 if(!data&&!error)return <div className="matches-loading"><LoaderCircle className="spin"/> Checking your prediction results...</div>;
 if(error&&!data)return <section className="empty-state"><BarChart3 size={34}/><h2>Prediction dashboard unavailable</h2><p>{error}</p><button className="secondary-button" onClick={()=>load(true)}>Try Again</button></section>;
 const predictions=[...(data?.predictions||[])].sort((a,b)=>{const aTime=a.kickoff_utc?Date.parse(a.kickoff_utc):Number.NaN;const bTime=b.kickoff_utc?Date.parse(b.kickoff_utc):Number.NaN;const aSort=Number.isFinite(aTime)?aTime:Number.POSITIVE_INFINITY;const bSort=Number.isFinite(bTime)?bTime:Number.POSITIVE_INFINITY;return aSort-bSort||b.id-a.id});const pending=predictions.filter(p=>p.result_status==="PENDING").length;const visiblePredictions=predictions.filter(p=>filter==="ALL"||p.result_status===filter);
 return <div className="predictions-dashboard">
  <style>{`.predictions-dashboard{max-width:980px}.prediction-header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.prediction-header-actions{display:flex;align-items:center;gap:10px}.prediction-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.prediction-stats section{padding:18px;border:1px solid #1d354e;border-radius:15px;background:linear-gradient(145deg,#0d2034,#091625);display:flex;align-items:center;gap:13px}.prediction-stats svg{color:#7cf3c7}.prediction-stats section div{display:flex;flex-direction:column;gap:4px}.prediction-stats span,.prediction-pick span,.prediction-result span{font-size:9px;font-weight:900;letter-spacing:.1em;color:#7088a3}.prediction-stats strong{font-size:22px}.prediction-filters{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.prediction-filters button{border:1px solid #29445f;border-radius:10px;background:#0b1d30;color:#9cb0c7;padding:9px 13px;font-weight:750;cursor:pointer}.prediction-filters button.active{border-color:#7cf3c7;color:#7cf3c7;background:rgba(124,243,199,.08)}.prediction-history{display:grid;gap:10px;margin-top:20px}.prediction-history-row{display:grid;grid-template-columns:minmax(0,1fr) 180px 150px;align-items:center;gap:18px;padding:17px 18px;border:1px solid #1d354e;border-radius:14px;background:#0a192a}.prediction-match-name{display:flex;align-items:center;gap:12px;min-width:0}.prediction-match-icon{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:rgba(124,243,199,.09);color:#7cf3c7;flex:0 0 auto}.prediction-match-name>div,.prediction-pick,.prediction-result{display:flex;flex-direction:column;gap:4px}.prediction-match-name strong{font-size:13px}.prediction-match-name strong span{color:#58718e;font-weight:600;margin:0 3px}.prediction-match-name small{color:#7289a3}.prediction-pick strong{color:#eaf4ff;font-size:13px}.prediction-result strong{font-size:12px}.prediction-result.pending strong{color:#f1c876}.prediction-result.correct strong{color:#7cf3c7}.prediction-result.incorrect strong{color:#ef9ba1}.result-detail{color:#7289a3;font-size:10px!important;font-weight:600!important}@media(max-width:760px){.prediction-header{align-items:flex-start;flex-direction:column}.prediction-stats{grid-template-columns:1fr 1fr}.prediction-history-row{grid-template-columns:1fr}.prediction-pick,.prediction-result{padding-left:50px}}@media(max-width:480px){.prediction-stats{grid-template-columns:1fr}}`}</style>
  <div className="prediction-header"><div><span className="eyebrow">PREDICTION CENTER</span><h1>Your predictions</h1><p>Your fan-pick history, completed results, and prediction accuracy in one place.</p></div><div className="prediction-header-actions"><button className="secondary-button" disabled={refreshing} onClick={()=>load(true)}>{refreshing?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>} {refreshing?"Checking...":"Refresh Results"}</button></div></div>
  <div className="prediction-stats"><section><Target size={19}/><div><span>TOTAL PICKS</span><strong>{predictions.length}</strong></div></section><section><Clock3 size={19}/><div><span>AWAITING RESULTS</span><strong>{pending}</strong></div></section><section><CheckCircle2 size={19}/><div><span>SCORED PICKS</span><strong>{data?.scored??0}</strong></div></section><section><CheckCircle2 size={19}/><div><span>ACCURACY</span><strong>{data?.accuracy_percent==null?"—":`${data.accuracy_percent}%`}</strong></div></section></div>
  {error&&<div className="quiz-complete-note">{error}</div>}
  {data?.notice&&<div className="quiz-complete-note">{data.notice}</div>}
  <div className="prediction-filters" role="group" aria-label="Filter prediction history">{(["ALL","PENDING","CORRECT","INCORRECT"] as const).map(status=><button key={status} type="button" aria-pressed={filter===status} className={filter===status?"active":""} onClick={()=>setFilter(status)}>{status==="ALL"?"All picks":status==="PENDING"?"Pending":status==="CORRECT"?"Correct":"Incorrect"} ({status==="ALL"?predictions.length:predictions.filter(p=>p.result_status===status).length})</button>)}</div>
  {!predictions.length?<section className="empty-state"><Target size={34}/><h2>No predictions yet</h2><p>Go to Matches and make your first prediction.</p></section>:!visiblePredictions.length?<section className="empty-state"><Target size={34}/><h2>No {filter.toLowerCase()} predictions</h2><p>Try another filter to view your saved picks.</p></section>:<div className="prediction-history">{visiblePredictions.map(item=><article className="prediction-history-row" key={item.id}><div className="prediction-match-name"><span className="prediction-match-icon">{item.result_status==="CORRECT"?<CheckCircle2 size={17}/>:item.result_status==="INCORRECT"?<XCircle size={17}/>:<BarChart3 size={17}/>}</span><div><strong>{item.home_team_name} <span>vs</span> {item.away_team_name}</strong><small>{item.kickoff_utc?new Date(item.kickoff_utc).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"Kickoff details unavailable"}</small></div></div><div className="prediction-pick"><span>YOUR PICK</span><strong>{outcomeLabel(item,item.predicted_outcome)}</strong></div><div className={`prediction-result ${item.result_status.toLowerCase()}`}><span>STATUS</span><strong>{item.result_status==="PENDING"?"Pending":item.result_status==="CORRECT"?"Correct ✓":"Incorrect"}</strong>{item.result_status!=="PENDING"&&<strong className="result-detail">{item.score?.home??"—"}–{item.score?.away??"—"} · {outcomeLabel(item,item.actual_outcome)}</strong>}</div></article>)}</div>}
 </div>
}
