import { BarChart3, CheckCircle2, Clock3, LoaderCircle, Target } from "lucide-react";
import { useEffect, useState } from "react";

type Prediction = { id:number; match_id:string; home_team_name:string; away_team_name:string; predicted_outcome:"HOME"|"DRAW"|"AWAY"; kickoff_utc?:string|null; created_at?:string|null };
type PredictionResponse = { predictions:Prediction[]; total:number; notice?:string|null };

function pickLabel(item:Prediction){if(item.predicted_outcome==="HOME")return item.home_team_name;if(item.predicted_outcome==="AWAY")return item.away_team_name;return "Draw"}

export default function PredictionsPage(){
 const [data,setData]=useState<PredictionResponse|null>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/v1/matches/predictions").then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.detail||"Could not load predictions.");return p}).then(setData).catch(e=>setError(e instanceof Error?e.message:"Could not load predictions."))},[]);
 if(!data&&!error)return <div className="matches-loading"><LoaderCircle className="spin"/> Loading prediction dashboard...</div>;
 if(error)return <section className="empty-state"><BarChart3 size={34}/><h2>Prediction dashboard unavailable</h2><p>{error}</p></section>;
 const predictions=data?.predictions||[];
 return <div className="predictions-dashboard">
  <style>{`.predictions-dashboard{max-width:980px}.prediction-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.prediction-stats section{padding:18px;border:1px solid #1d354e;border-radius:15px;background:linear-gradient(145deg,#0d2034,#091625);display:flex;align-items:center;gap:13px}.prediction-stats svg{color:#7cf3c7}.prediction-stats section div{display:flex;flex-direction:column;gap:4px}.prediction-stats span,.prediction-pick span,.prediction-result span{font-size:9px;font-weight:900;letter-spacing:.1em;color:#7088a3}.prediction-stats strong{font-size:22px}.prediction-history{display:grid;gap:10px;margin-top:20px}.prediction-history-row{display:grid;grid-template-columns:minmax(0,1fr) 180px 120px;align-items:center;gap:18px;padding:17px 18px;border:1px solid #1d354e;border-radius:14px;background:#0a192a}.prediction-match-name{display:flex;align-items:center;gap:12px;min-width:0}.prediction-match-icon{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:rgba(124,243,199,.09);color:#7cf3c7;flex:0 0 auto}.prediction-match-name>div,.prediction-pick,.prediction-result{display:flex;flex-direction:column;gap:4px}.prediction-match-name strong{font-size:13px}.prediction-match-name strong span{color:#58718e;font-weight:600;margin:0 3px}.prediction-match-name small{color:#7289a3}.prediction-pick strong{color:#eaf4ff;font-size:13px}.prediction-result.pending strong{color:#f1c876;font-size:12px}@media(max-width:760px){.prediction-stats{grid-template-columns:1fr}.prediction-history-row{grid-template-columns:1fr}.prediction-pick,.prediction-result{padding-left:50px}}`}</style>
  <span className="eyebrow">PREDICTION CENTER</span><h1>Your predictions</h1><p>Your fan-pick history lives here separately from the match center. Results, accuracy, and ML comparison can plug into this dashboard next.</p>
  <div className="prediction-stats"><section><Target size={19}/><div><span>TOTAL PICKS</span><strong>{predictions.length}</strong></div></section><section><Clock3 size={19}/><div><span>AWAITING RESULTS</span><strong>{predictions.length}</strong></div></section><section><CheckCircle2 size={19}/><div><span>ACCURACY</span><strong>—</strong></div></section></div>
  {data?.notice&&<div className="quiz-complete-note">{data.notice}</div>}
  {!predictions.length?<section className="empty-state"><Target size={34}/><h2>No predictions yet</h2><p>Go to Matches and make your first fan prediction.</p></section>:<div className="prediction-history">{predictions.map(item=><article className="prediction-history-row" key={item.id}><div className="prediction-match-name"><span className="prediction-match-icon"><BarChart3 size={17}/></span><div><strong>{item.home_team_name} <span>vs</span> {item.away_team_name}</strong><small>{item.kickoff_utc?new Date(item.kickoff_utc).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"Kickoff details unavailable"}</small></div></div><div className="prediction-pick"><span>YOUR PICK</span><strong>{pickLabel(item)}</strong></div><div className="prediction-result pending"><span>STATUS</span><strong>Pending</strong></div></article>)}</div>}
 </div>
}
